version: '3.8'

services:
  web:
    build: .
    ports:
      - "8889:8889"
    volumes:
      - .:/app
    environment:
      - UPLOAD_FOLDER=/app/assets
      - FLASK_APP=app:app

  gltf-viewer:
    image: bwasty/gltf-viewer
    volumes:
      - ./assets:/input
